---
- name: Create ansible service user
  user: name={{ ansible_access_username }} group=users groups=wheel append=yes uid=2999 
  sudo: yes

- name: Log key that is being deployed
  debug: var=ansible_access_public_key_file

- name: Load Ansible User Key
  authorized_key: user={{ ansible_access_username }} key="{{ lookup('file', ''+ansible_access_public_key_file ) }}" manage_dir=no
  sudo: yes

- name: Sudoers | update sudoers file and validate
  lineinfile: "dest='/etc/sudoers.d/00-ansible-access-user' owner=root group=root mode=0440
              insertafter=EOF
              line='{{ ansible_access_username }} ALL=(ALL) NOPASSWD: ALL'
              regexp='{{ ansible_access_username }} ALL=.ALL. NOPASSWD: ALL'
              state=present
              create=yes
              validate='visudo -cf %s'"
  sudo: yes

- name: Sudoers | update sudoers file and validate
  lineinfile: "dest='/etc/sudoers.d/00-ansible-access-user' owner=root group=root mode=0440
              insertafter=EOF
              line='Defaults:{{ ansible_access_username }}    !requiretty'
              regexp='Defaults.{{ ansible_access_username }}    .requiretty'
              state=present
              create=yes
              validate='visudo -cf %s'"
  sudo: yes
